# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28786e9ada3daf045d05eda4af960bf8b6ef6fd87806344972b4838c5c02f2471a0e018bead39eaeec39f51b1c9e7ee055364a52337982feb06dbfd0556e0c53

test:
  secret_key_base: 2795815e7edd61e30b3cbbad74b6e629996076abffab87eac871bc7e2f1a39d202344033424f5e24f3cdb151269c206e13940a99fdac099f85131fe77d09a2e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
